# Generated by Django 5.1.4 on 2024-12-19 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='specialization',
        ),
        migrations.AddField(
            model_name='trainer',
            name='spec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='trainer.specialization'),
        ),
    ]
