# Generated by Django 5.1.4 on 2024-12-20 09:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_specialization_remove_trainer_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
